### ISSUE TITLE
TeX parse error: Undefined control sequence \argmax

### ISSUE THREAD

**Issue by qqhann** [yousefvand/mathover#2]
Thanks for making this extension!

When I use it, it cannot parse `\argmax` which IMO is common usage.
Is this a MathJax-node problem, or does it need configurations?
How can I get this fixed?

**Comment by yousefvand** [comment]
You're welcome
I strip text markers from your text and send the rest of your line of comment to the `mathjax-node` library. If any error happens, this is the library to be blamed. BTW, I don't maintain this extension actively.
